### PR TITLE
feat: add custom configuration

### PR DESCRIPTION
**Pull request by viniciusguardieirozup**
I create a custom configuration to the task to allow some changes on title and linkTitle, solving the problem on issue: #1

### CODE REVIEW

**Comment by dschuermann** [comment]
Great thanks! Haven't expected to get contributions to this hacky plugin ;)

**Comment by viniciusguardieirozup** [comment]
Haha, when you publish a new version, could you tell me and update the readme specifying the new version, please?

**Comment by dschuermann** [comment]
thanks for the reminder. 2.0 is building right now on Jitpack.

**Comment by viniciusguardieirozup** [comment]
Thanks!

**Pull request merged**
